### ISSUE TITLE
Cannot install tilp on Kubuntu 18.04

### ISSUE THREAD

**Issue by aim-gaming** [debrouxl/tilp_and_gfm#13]
I apologize in advance if anything in this seems like a stupid question, I have some experience with linux, but I definitely wouldn't call myself an expert.

I can't seem to install tilp properly on Kubuntu 18.04. I tried using the install_tilp.sh script on the site (http://lpg.ticalc.org/prj_tilp/download/install_tilp.sh), but it complained about all of the libti* libraries being the wrong version. So, I compiled and installed all of the libraries individually. This solved the complaints about wrong library versions, and the install script proceeded. However, it failed with the error: `gcc: error: X_LDFLAGS@: No such file or directory`. The only thing I can think of that I did differently than the default is that I configured libticables with `--enable-libusb10`, because it complained about not having libusb otherwise.

 So, I tried to install tilp by itself, by downloading the source and following the instructions in the README.linux. Running `autoreconf -i -f -v` resulted in: 

autoreconf: Entering directory .'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:134: error: possibly undefined macro: AC_PATH_KDE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

I think that the `possibly undefined macro: AC_PATH_KDE` may be because I'm using KDE, but I couldn't find anything about it on Google.

I'm running Kubuntu 18.04 with all of the latest libti* libraries, with make, autoconf, gfm, autoreconf, automake, libusb1.0

Attached is the output of the install_tilp.sh script.
[tilp_installer_output.txt](https://github.com/debrouxl/tilp_and_gfm/files/1763625/tilp_installer_output.txt)

**Comment by debrouxl** [comment]
* the X_LDFLAGS error was already reported yesterday, and I've just applied (with a force push of the master branch) the prospective fix I mentioned yesterday to the other person :)
In /home/andrew/lpg/tilp/tilp_and_gfm/ , you'll have to run
$ git pull
$ git reset --hard origin/master
before restarting install_tilp.sh .

* the AC_PATH_KDE error is precisely what I was trying to fix by removing support for severely outdated KDE versions, at the current Git HEAD. It seems that you're using a source version older than that, the line number of AC_PATH_KDE is now 135 (but it's commented out) :)

**Comment by aim-gaming** [comment]
The install goes quite a bit further now, but still doesn't finish. Now, it gives the error:

 /usr/bin/ld: tilp-tilp_screen.o: undefined reference to symbol 'compress'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:486: recipe for target 'tilp' failed
make[2]: *** [tilp] Error 1
make[2]: Leaving directory '/home/andrew/lpg/tilp/tilp_and_gfm/tilp/trunk/src'
Makefile:516: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/andrew/lpg/tilp/tilp_and_gfm/tilp/trunk'
Makefile:427: recipe for target 'all' failed
make: *** [all] Error 2

Attached is the output of the install script.
[intaller_output.txt](https://github.com/debrouxl/tilp_and_gfm/files/1764513/intaller_output.txt)

**Comment by debrouxl** [comment]
Alright, try again after another pull + reset --hard :)

I had removed @LIBZ@ from tilp_LDADD after seeing it in acinclude.m4 along the others... but TILP really needs it, and it's already part of configure.ac.

**Comment by aim-gaming** [comment]
The installation finishes now! I had to upgrade the libti* libraries (the ones on the site aren't quite up to date), but it's working now. Thanks for your help!

**Comment by debrouxl** [comment]
You're welcome, thanks for your tests :)

**Comment by siealfy** [comment]
i need conics periodictablehub apps reinstalled

**Comment by debrouxl** [comment]
Did you use the install script from this repo, https://github.com/debrouxl/tilp_and_gfm/raw/master/tilp/trunk/build/scripts/install_tilp.sh , to install libti*+gfm+tilp, after installing the required build dependencies ?
