### ISSUE TITLE
configure.ac:53: error: possibly undefined macro: AC_PROG_INTLTOOL

### ISSUE THREAD

**Issue by SpaceboyRoss01** [debrouxl/tilp_and_gfm#14]
I was trying to compile using the `install_tilp.sh` program, but I got an error.
```
autoreconf: running: /usr/bin/autoconf --force
configure.ac:53: error: possibly undefined macro: AC_PROG_INTLTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by debrouxl** [comment]
Did you install all of the dependencies listed by install_tilp.sh ? This message is usually caused by not having done so, which is why I'm asking.
Also, you didn't mention which OS type and flavour you're using ;)

**Comment by SpaceboyRoss01** [comment]
I fixed it by installing intltool using apt
