### ISSUE TITLE
Compile failing on Ubuntu 19.04

### ISSUE THREAD

**Issue by fbmoose48** [debrouxl/tilp_and_gfm#27]
when running the install_tilp.sh all is fine until it begins the check for libraries and the glib package check begins, then it returns

./configure: line 10108: syntax error near unexpected token `GLIB,'
./configure: line 10108: `PKG_CHECK_MODULES(GLIB, glib-2.0 >= 2.6.0)'

and stops. Any thought on how to resolve this?

**Comment by fbmoose48** [comment]
Manual install returns several errors after autoreconf, including:

configure.ac:58: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:53: error: possibly undefined macro: AC_PROG_INTLTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:58: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by adriweb** [comment]
Looks like you didn't install all the required dependencies first. Look at this line: https://github.com/debrouxl/tilp_and_gfm/blob/master/tilp/trunk/build/scripts/install_tilp.sh#L213

**Comment by fbmoose48** [comment]
thank you, issue closed
