### ISSUE TITLE
"Msg: illegal operation or argument" when connecting

### ISSUE THREAD

**Issue by creallfluharty** [debrouxl/tilp_and_gfm#36]
Per recommendation over at Cemetech ([post](https://www.cemetech.net/forum/viewtopic.php?p=284888)), I thought I'd ask here.

As I described it over there:

>I'm currently using TiLP to try and dump the ROM of my TI84+ CE, but I'm running into an issue communicating with it. At this point, I know that my calculator is connected (it shows up under device manager), but scanning simply results in an empty list and a message saying "done!".
>![image](https://user-images.githubusercontent.com/32851582/77836804-6f1c2480-7127-11ea-8745-1cefab8d26e1.png)
>
>(this is not my question/issue, but I can imagine it being related)
>
>If I select any of ports 1-3, I get a "failed to open the USB device" error, so I believe it is on Port #4 (I'm sure there's a better way of determining that).
>
>Port #4, however, gives a somewhat nastier "illegal operation or argument".
>
>Pressing "OK" at this point:
>![image](https://user-images.githubusercontent.com/32851582/77836821-83f8b800-7127-11ea-905a-afa927930765.png)
>Results in:
>![image](https://user-images.githubusercontent.com/32851582/77836825-89ee9900-7127-11ea-97d9-41ef61d728a1.png)
>>Msg: illegal operation or argument.
>>Cause: the program which uses this library is buggy. Fire-up the developer!

**Am I misconfiguring something?**

### Additional info:
OS: Windows 10
Calc: TI84PlusCE 5.01.0012
TiLP: 1.19

(If any logs would help, please let me know. ATM, I'm not exactly sure how I would get that on Windows though)

**Comment by debrouxl** [comment]
The fact that nothing is detected isn't good, and that's what we need to fix first :)
Did you:
* use Zadig once, as described in the README, to work around stupid Windows driver signing requirements (which are just plain silly because Zadig self-signs something and Windows becomes happy with it) ?
* use the libusb-win32 filter driver, as described at the same location, if you installed TI-Connect CE before installing TILP ?

**Comment by creallfluharty** [comment]
Very sorry, I should have tried that! You said the same thing on Cemetech, but I wasn't sure where the README was<sup>1</sup>. I may still need to use Zadig, but installing the filter driver seemed to be enough! I was able to find the calculator via the scan function, and dump the from in another few minutes!

Sorry to bother! Thank you for the awesome software and support!

<sub><sup>1</sup>Apparently I didn't really process the fact that this repo contains two separate projects with READMEs under each. In the unlikely case that anyone else finds themself in the same situation, here's [a direct link][1]</sub>

[1]: https://github.com/debrouxl/tilp_and_gfm/blob/master/tilp/trunk/README.win32

**Comment by debrouxl** [comment]
You're welcome :)
You don't have to be sorry, there's clearly room for improvement on my side, e.g. it adding proper READMEs at the root of both the tilibs and the tilp_and_gfm repo, or opening the Win32 README unconditionally at the end of a successful install by the InnoSetup installer.
