### ISSUE TITLE
Support fo the Ti-80

### ISSUE THREAD

**Issue by Izder456** [debrouxl/tilp_and_gfm#37]
This isn't really an issue but more of a question,
I saw in a Cemetech forum post that the Ti-80 has soldering pads for an i/o port. Is it possible, to solder an i/o port to the Ti-80 and link it to TiLP?

This would be especially useful, to dump a rom of the calculator because these calculators are dying because of the life expectancy of the rom chip. 

link to the Cemetech post:
https://www.cemetech.net/forum/viewtopic.php?p=284990#284990

**Comment by debrouxl** [comment]
mr womp womp beat me to replying that the TI-80's ROM only provides support for taking screenshots remotely :)
libti*/tilp do already support the TI-80 VSC; the support was contributed by Randy Compton, Zeroko on Cemetech, who posted in that topic.
