### ISSUE TITLE
Sync Clock With PC Always Sets Clock to UTC

### ISSUE THREAD

**Issue by JLP04** [debrouxl/tilp_and_gfm#46]
When I click the button to sync the calculator time with my PC's time, tilp shows it's setting the calculator time to the current local time but the calculator itself ends up getting set to the current UTC time.

**Comment by JLP04** [comment]
Fixed.

**Comment by debrouxl** [comment]
Er, fixed ?

**Comment by JLP04** [comment]
Yeah, I tried it this morning and it seems to have magically fixed itself, unless its a difference with the way macOS Monterrey is reporting time vs. Big Sur

**Comment by adriweb** [comment]
Might be worth checking if it's related to DST

**Comment by debrouxl** [comment]
That's what I was going to suggest, indeed.
