### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by nfitzen** [debrouxl/tilp_and_gfm#51]
Would you consider adding a [free software] license to the code, such as [`GPL-3.0-or-later`]?

(Note that all non-trivial contributors would need to agree to whatever license you pick. Also, see [REUSE](https://reuse.software/) and [the GNU Project's license recommendations][1] for further info. And, just in case, I'm not a lawyer, and this isn't legal advice.)

[1]: https://www.gnu.org/licenses/license-recommendations.html

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"

[free software]: https://www.gnu.org/philosophy/free-sw.html "Free as in freedom, not price."

**Comment by adriweb** [comment]
It is already GPL (and the tilibs as well)

**Comment by debrouxl** [comment]
Indeed :)
There's no licensing information at the root of the repo, but all parts of the stack are under the GPLv2 only, for some if not all of them.

**Comment by nfitzen** [comment]
Ah, I missed that. Sorry! I'm closing this now.
